---
# Persistent Odoo deployment playbook.
#
# The following variables come from the ansible-operator
# - meta.namespace
# - meta.name (from the name of the CR)

- hosts: localhost
  gather_facts: no
  tasks:
  - name: Set up PostgreSQL
    include_role:
      name: ./roles/postgresql
    vars:
      _postgresql_namespace: "{{ meta.namespace }}"
      _postgresql_name: "postgresql-{{ meta.name }}"
      _postgresql_database_name: "odoodb"
      _postgresql_user: "odoo"
      _postgresql_password: "odoo"
      _postgresql_volume_size: "{{ postgresql_volume_size|default('4Gi') }}"
      _postgresql_image: "{{ postgresql_image | default('ursa/postgresql-13.0') }}"
      _postgresql_image_tag: "{{ postgresql_image_tag|default('latest') }}"

  - name: Set up Odoo
    include_role:
      name: ./roles/odoo
    vars:
      _odoo_namespace: "{{ meta.namespace }}"
      _odoo_name: "odoo-{{ meta.name }}"
      _odoo_route: "{{ odoo_route | default('') }}"
      _odoo_image: "{{ odoo_image | default('ursa/odoo-14.0') }}"
      _odoo_image_tag: "{{ odoo_image_tag | default('latest') }}"
      _odoo_admin_passwd: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
      _odoo_admin_user_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
      _odoo_postgresql_service_name: "postgresql-{{ meta.name }}"
      _odoo_postgresql_database_name: "odoodb"
      _odoo_postgresql_user: "odoo"
      _odoo_postgresql_password: "odoo"
      _odoo_volume_size: "{{ odoo_volume_size | default('4Gi') }}"
