# permissions for end users to view odooes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odoo-viewer-role
rules:
- apiGroups:
  - apps.odoo-community.org
  resources:
  - odooes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.odoo-community.org
  resources:
  - odooes/status
  verbs:
  - get
