# permissions for end users to edit odooes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odoo-editor-role
rules:
- apiGroups:
  - apps.odoo-community.org
  resources:
  - odooes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.odoo-community.org
  resources:
  - odooes/status
  verbs:
  - get
