---
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: odoo-admin-rules
rules:
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list- patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - gpte.opentlc.com
  resources:
  - odoos
  - odoos/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
