kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odoo-operator
subjects:
- kind: ServiceAccount
  name: odoo-operator
  namespace: odoo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odoo-admin-rules
