apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: odoo-operator
  template:
    metadata:
      labels:
        name: odoo-operator
    spec:
      serviceAccountName: odoo-operator
      containers:
        - name: odoo-operator
          # Replace this with the built image name
          image: quay.io/ursais/odoo-operator:v0.0.1
          command:
          - odoo-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "odoo-operator"
