= odoo

== Requirements

This role is designed to set up Odoo on an OpenShift cluster. The intended use for this role is in an Operator. The role does not set up Kubernetes controllers (like Deployments or ReplicaSets) but creates the Odoo Pod directly - this is the preferred approach to be used by an Operator.

This role also requires a PostgreSQL Database to be running in the same OpenShift project as the Odoo Server. This database needs to be set up first.

== Role Variables

[cols="2,1,1,4",options="header"]
|====
|Variable Name|Default|Required|Description
|_odoo_namespace|odoo|Yes|Project Name to install Odoo into
|_odoo_name|odoo|Yes|Name of the Odoo service
|_odoo_ssl|False|No|Set up HTTPS for the Odoo Route
|_odoo_postgresql_service_name|postgresql|Yes|Name of the PostgreSQL service to connect (should be listening on port 5432)
|_odoo_postgresql_database_name|postgresql|Yes|Name of Database connect to
|_odoo_postgresql_user|postgresql|Yes|Database User Name
|_odoo_volume_size|1Gi|No|Size of Persistent Volume to be created
|_odoo_memory_request|512Mi|No|Minimum Memory Requirement
|_odoo_memory_limit|512Mi|No|Maximum Memory Requirement
|_odoo_cpu_request|200m|No|Minimum CPU Requirement
|_odoo_cpu_limit|500m|No|Maximum CPU Requirement
|_odoo_wait_for_init|true|No|Wait for the database pod to be running and ready
|_odoo_image|docker.io/wkulhanek/odoo|Yes|Container image for Odoo
|_odoo_image_tag|latest|Yes|Tag for Odoo container image
|_odoo_state|present|No|`present` to install, `absent` to remove
|====

== Dependencies

* k8s module.
* Running PostgreSQL database listening on port 5432
* Working .kube/config configuration.
* The Project/Namespace must exist

== Example Playbook

[source,yaml]
----
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Set up PostgreSQL
    include_role:
      name: ./roles/postgresql
    vars:
      _postgresql_namespace: "odoo"
      _postgresql_name: "postgresql-odoo"
      _postgresql_database_name: "odoodb"
      _postgresql_user: "odoo"
      _postgresql_password: "odoo"
      _postgresql_volume_size: "4Gi"

  - name: Set up Odoo
    include_role:
      name: ./roles/odoo
    vars:
      _odoo_namespace: "odoo"
      _odoo_name: "odoo"
      _odoo_ssl: "True|
      _odoo_volume_size: "4Gi"
      _odoo_postgresql_service_name: "postgresql-odoo"
      _odoo_postgresql_database_name: odoodb
      _odoo_postgresql_user: odoo
----

== License

BSD
